from enum import Enum, auto


class CategoryType(Enum):
    MATHEMATICS = auto()
    SPORT = auto()
    MUSIC = auto()
    SLANG = auto()
    BOTANIC = auto()
    PLURAL = auto()
    MARINE = auto()
    HISTORY = auto()
    THEOLOGY = auto()
    ZOOLOGY = auto()
    METAPHOR = auto()
    PSYCHOLOGY = auto()
    ASTRONOMY = auto()
    GEOGRAPHY = auto()
    GRAMMAR = auto()
    MILITARY = auto()
    PHYSICS = auto()
    PHILOSOPHY = auto()
    MEDICAL = auto()
    THEATER = auto()
    ECONOMY = auto()
    LAW = auto()
    ANATOMY = auto()
    GEOMETRY = auto()
    BUSINESS = auto()
    PEDAGOGY = auto()
    TECHNOLOGY = auto()
    LOGIC = auto()
    LITERATURE = auto()
    CINEMA = auto()
    TELEVISION = auto()
    ARCHITECTURE = auto()
    TECHNICAL = auto()
    SOCIOLOGY = auto()
    BIOLOGY = auto()
    CHEMISTRY = auto()
    GEOLOGY = auto()
    INFORMATICS = auto()
    PHYSIOLOGY = auto()
    METEOROLOGY = auto()
    MINERALOGY = auto()
